# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text=b'Stuff about yourself.')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'A programming language or coding framework name.', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b"Your project's name.", max_length=50)),
                ('description', models.TextField(help_text=b"Your project's description, what it does, how it works, download links etc.")),
                ('thumbnail', models.ImageField(blank=True, upload_to=b'')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name=b'Publish Date')),
                ('languages', models.ManyToManyField(help_text=b'The language(s) your project is based on.', to='coding_portfolio.Language')),
            ],
        ),
    ]
