# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(help_text='Stuff about yourself.'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='A programming language or coding framework name.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text="Your project's description, what it does, how it works, download links etc."),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(help_text='The language(s) your project is based on.', to='coding_portfolio.Language'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text="Your project's name.", max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
