# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_portfolio', '0003_question_answer_slide_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide_Images',
            new_name='Slide_Image',
        ),
    ]
